name: Prettier Format Check

on:
  push:
    branches:
      - main
      - '**'

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.4'

      - name: Install dependencies
        run: npm ci --include-dev

      - name: Check formatting
        run: npm run format:check
